config/routes.rb
Gym::Application.routes.draw do
  devise_for :profiles

  resources :measure_units

  resources :profiles do
    resources :diets do 
      resources :food_line_items  
    end 
  end

  match 'get_diets' => "diets#get_diets"
  
  resources :foods do 
      resources :nutritional_informations
      get :change_type, on: :collection
  end

  resources :types

  root to: "profiles#index"
end

app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :name, :type_id, :nutritional_information
  validates_presence_of :name
  belongs_to :type
  has_one :nutritional_information
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_filter :verify
  before_filter :load_types, :only => [:index, :new, :edit, :create, :update] 
  respond_to :html, :json

  def verify
    unless profile_signed_in?
      redirect_to new_profile_session_path()
    end
  end 

  def load_types 
    @foodTypes = Type.all.collect { |t| [t.name, t.id] }
  end

  def change_type
    @foods = Food.includes(:type).where( type_id: params['type']['type_id']).paginate(page: params[:page])
    render partial: 'foods', locals: { foods: @foods }
  end

  # GET /foods
  # GET /foods.json
  def index
    @food_type_id = @foodTypes.first

    if params['type']
      @foods = Food.includes(:type).includes(:nutritional_information).where( type_id: params['type']['type_id']).paginate(page: params[:page])
    else
      @foods = Food.includes(:type).includes(:nutritional_information).where( type_id: @food_type_id).paginate(page: params[:page])
    end

    respond_with @foods
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @food = Food.find(params[:id])
    respond_with(@food)
  end

  # GET /foods/new
  # GET /foods/new.json
  def new
    @food = Food.new(:nutritional_information => NutritionalInformation.new)
    respond_with(@food)
  end

  # GET /foods/1/edit
  def edit
    @food = Food.find(params[:id])
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.create(params[:food])
    redirect_to foods_url
  end

  # PUT /foods/1
  # PUT /foods/1.json
  def update
    @food = Food.find(params[:id])

    respond_to do |format|
      if @food.update_attributes(params[:food])
        format.html { redirect_to foods_path(), notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_url
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_foods.html.erb
<%= will_paginate :params => { :controller => "foods", :action => "index" } %>

<table id="foods" class="table table-striped">
  <thead>
    <tr>
     
      <th>Categoria</th>
      <th>Descripción</th>
      <th>Información nutricional</th>

      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
        <% @foods.each do |food| %>
        <tr>
          <td><%= food.type.name %></td>
          <td><%= food.name %></td>
          
          <td>


            <% if food.nutritional_information %>
            <%= link_to t('.edit', :default => 'ver'),
                        food_nutritional_information_path(food,food.nutritional_information),
                        :class => 'btn btn-mini' %>
            <% else %>
            <%= link_to t('.edit', :default => 'cargar'),
                            new_food_nutritional_information_path(food),
                            :class => 'btn btn-mini' %>

            <% end %>
          </td>

          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_food_path(food), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        food_path(food),
                        :method => :delete,
                        :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                        :class => 'btn btn-mini btn-danger' %>
          </td>
        </tr>
<% end %>
  </tbody>
</table>
<%= will_paginate :params => { :controller => "foods", :action => "index" } %>

app/views/foods/_form.html.erb
<%= simple_form_for(@food, :html => {:class => 'form-horizontal' }) do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field', hint: "Debes ingresar un nombre." %>
      <%= f.error :name %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :type_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :type_id, @foodTypes %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                foods_path, :class => 'btn' %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<%- model_class = @food.class -%>
<h1>Editar Alimento</h1>
<br />
<%= render :partial => 'form' %>

app/views/foods/index.html.erb
<h1>Alimentos</h1>

<div class="alert alert-info">
  <a class="close" data-dismiss="alert">×</a>
  Acá podés crear alimentos, los vas a necesitar para la dieta.
</div>

<%= form_tag(change_type_foods_path, :method => 'get', id: 'change_form') do  %>
<div class="control-group">
    <label for='type_id'> Categoria </label>
    <div class="controls">
      <%= select_tag :type_id, options_for_select(@foodTypes) %>
    </div>
</div>
<% end %>

<div id='food_table'>
  <%= render 'foods', locals: {foods: @foods} %>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_food_path,
            :class => 'btn btn-primary' %>

app/views/foods/new.html.erb
<%- model_class = @food.class -%>
<h1>Nuevo Alimento</h1><br />
<%= render :partial => 'form' %>

app/views/foods/show.html.erb
<%- model_class = @food.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:name) %>:</strong><br>
  <%= @food.name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:type_id) %>:</strong><br>
  <%= @food.type_id %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              foods_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_food_path(@food), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              food_path(@food),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>