config/routes.rb
Gym::Application.routes.draw do
  devise_for :profiles

  resources :measure_units

  resources :profiles do
    resources :diets do 
      resources :food_line_items  
    end 
  end

  match 'get_diets' => "diets#get_diets"
  
  resources :foods do 
      resources :nutritional_informations
      get :change_type, on: :collection
  end

  resources :types

  root to: "profiles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= yield(:title).presence || "Gym" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
          <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Gym</a>

          <% if profile_signed_in? %>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Perfil", profiles_path()%></li>
              <li><%= link_to "Alimentos", foods_path()%></li>
              <li><%= link_to "Categorias", types_path()  %></li>
              <li><%= link_to "Unidades", measure_units_path()  %></li>

            </ul>
            <form class="navbar-search pull-left">
  <input type="text" class="search-query" placeholder="Search">
</form>
          </div><!--/.nav-collapse -->
          <% end %>
        </div>
      </div>
            <div id="user_nav" style='float:right; margin-right:100px'>
                <% if profile_signed_in? %>
                  Signed in as <%= current_profile.email %>. Not you?
                  <%= link_to "Sign out", destroy_profile_session_path,  method: :delete %>
                <% else %>
                  <%= link_to "Sign up", new_profile_registration_path %> or
                  <%= link_to "Sign in", new_profile_session_path %>
                <% end %>
              </div>
    </div>

    <div class="container">
      <div class="content">        
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>